assignment1: q1a1 q2a1 q3a1 q4a1 q5a1

q1a1: q1a1.c
		gcc -o q1a1 q1a1.c -Wall
q2a1: q2a1.c
		gcc -o q2a1 q2a1.c -Wall
q3a1: q3a1.c
		gcc -o q3a1 q3a1.c -Wall
q4a1: q4a1.c
		gcc -o q4a1 q4a1.c -Wall
q5a1: q5a1.c
		gcc -o q5a1 q5a1.c -Wall
clean:
		-rm *.o q1a1 q2a1 q3a1 q4a1 q5a1