assignment2: dllk llk q q1a2 q3a2 sort stack
dllk: dllk.c
		gcc -o dllk dllk.c -Wall
llk: llk.c
		gcc -o llk llk.c -Wall
q: q.c
		gcc -o q q.c -Wall
q1a2: q1a2.c
		gcc -o q1a2 q1a2.c -Wall
q3a2: q3a2.c
		gcc -o q3a2 q3a2.c -Wall
sort: sort.c
		gcc -o sort sort.c -Wall
stack: stack.c
		gcc -o stack stack.c -Wall
clean:
		-rm *.o dllk llk q q1a2 q3a2 sort stack